import {
	integer,
	pgTable,
	primaryKey,
	text,
	timestamp,
	uuid,
} from 'drizzle-orm/pg-core';
import { id, softDelete, timestamps } from '../src/pg';

export const teams = pgTable('teams', {
	id: id('identity'),
	name: text('name').notNull().unique('teams_name_unique'),
});

export const users = pgTable('users', {
	id: id(),
	email: text('email').notNull().unique('users_email_unique'),
	name: text('name'),
	age: integer('age'),
	teamId: integer('team_id').references(() => teams.id),
	...timestamps(),
	...softDelete(),
});

/** An `updatedAt` without `$onUpdate`: the repository sets it. */
export const posts = pgTable('posts', {
	id: integer('id').primaryKey().generatedAlwaysAsIdentity(),
	title: text('title').notNull(),
	rank: integer('rank').notNull(),
	updatedAt: timestamp('updated_at', { withTimezone: true, precision: 3 }),
});

export const memberships = pgTable(
	'memberships',
	{
		userId: uuid('user_id').notNull(),
		teamId: integer('team_id').notNull(),
		role: text('role').notNull(),
	},
	(t) => [primaryKey({ columns: [t.userId, t.teamId] })],
);

export const logs = pgTable('logs', {
	message: text('message').notNull(),
});

/** The DDL for the tables above, with named constraints the specs assert on. */
export const DDL = `
create table teams (
	id integer primary key generated by default as identity,
	name text not null constraint teams_name_unique unique
);
create table users (
	id uuid primary key default gen_random_uuid(),
	email text not null constraint users_email_unique unique,
	name text,
	age integer constraint users_age_check check (age >= 0),
	team_id integer constraint users_team_fk references teams (id),
	created_at timestamptz(3) not null default now(),
	updated_at timestamptz(3) not null default now(),
	deleted_at timestamptz(3)
);
create table posts (
	id integer primary key generated always as identity,
	title text not null,
	rank integer not null,
	updated_at timestamptz(3)
);
create table memberships (
	user_id uuid not null,
	team_id integer not null,
	role text not null,
	primary key (user_id, team_id),
	constraint memberships_role_unique unique (team_id, role)
);
create table logs (
	message text not null
);
`;
