import { integer, timestamp, uuid } from 'drizzle-orm/pg-core';

function uuidId() {
	return uuid('id').primaryKey().defaultRandom();
}

function identityId() {
	return integer('id').primaryKey().generatedByDefaultAsIdentity();
}

/**
 * An `id` primary key: a `uuid` with `default gen_random_uuid()`, or with
 * `'identity'`, an `integer generated by default as identity`. Spread it or
 * assign it: `{ id: id(), … }`.
 */
export function id(): ReturnType<typeof uuidId>;
export function id(kind: 'uuid'): ReturnType<typeof uuidId>;
export function id(kind: 'identity'): ReturnType<typeof identityId>;
export function id(kind: 'uuid' | 'identity' = 'uuid') {
	return kind === 'identity' ? identityId() : uuidId();
}

// Millisecond precision: a JavaScript `Date` has no more. At PostgreSQL's
// default of microseconds, a row's `createdAt` read back into a `Date` is not
// equal to the stored value, and a cursor on it repeats or skips rows.
const precise = { withTimezone: true, precision: 3 } as const;

/**
 * `createdAt` and `updatedAt`, as `created_at` and `updated_at`:
 * `timestamptz(3) not null default now()`. Drizzle sets `updatedAt` on every
 * update, through `$onUpdate`.
 */
export function timestamps() {
	return {
		createdAt: timestamp('created_at', precise).notNull().defaultNow(),
		updatedAt: timestamp('updated_at', precise)
			.notNull()
			.defaultNow()
			.$onUpdate(() => new Date()),
	};
}

/**
 * `deletedAt`, as `deleted_at`: a nullable `timestamptz(3)`. A repository on a
 * table with it soft-deletes.
 */
export function softDelete() {
	return {
		deletedAt: timestamp('deleted_at', precise),
	};
}
